### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by acandreva** [simoncorry/jquery.preloader#1]

**Comment by simoncorry** [comment]
Hey, I probably need to update the support for the transition event listeners. Can you link me to your site and provide the version of Firefox and the operating system you're testing on?

S

**Comment by acandreva** [comment]
I probably seem like a crazy person... Because it's working fine now. 
Site is allisoncandreva.com. And I'm testing on Firefox version 42 and Mac OS 10.9. But it might be a non issue now. 

Allison

**Comment by simoncorry** [comment]
Haha, it happens. I'll close it for now but feel free to reopen if you run into any other issues.

S
